---

- name: apply common configuration to all nodes
  hosts: all
  remote_user: centos

  roles:
    - common

- name: install and configure the manager
  hosts: manager
  remote_user: centos
  become: yes

  roles:
    - manager
