---

- name: apply common configuration to all nodes
  hosts: all
  remote_user: centos

  roles:
    - common

- name: install and configure the web
  hosts: web2
  remote_user: centos
  become: yes

  roles:
    - web
