---

- name: change hostname
  hostname:
    name: "{{team}}_{{var_hostname}}"

- name: create script log directory
  file:
    path: /var/log/script
    state: directory
    mode: 0774
    group: wheel

- name: Put profile on remote
  copy:
    src: "../files/addProfile.txt"
    dest: /etc/profile
    force: yes

- name: add a new user
  user: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    group: "{{ item.group }}"
    password: "{{ item.password }}"
  with_items: 
    - { "name":"{{MG_username}}", "state":"present", "group":"wheel", "password":"{{MG_password}}" }
    - { "name":"{{tech_username}}", "state":"present", "group":"wheel", "password":"{{tech_password}}" }
    - { "name":"{{OP_username}}", "state":"present", "group":"users", "password":"{{OP_password}}" }

- name: mkdir .ssh
  file: 
    dest: "{{ item.dest }}/.ssh/" 
    state: directory 
    owner: "{{ item.owner }}"
  with_items: 
    - { "dest":"{{MG_homedir}}", "owner":"{{MG_username}}" }
    - { "dest":"{{tech_homedir}}", "owner":"{{tech_username}}" }
    - { "dest":"{{OP_homedir}}", "owner":"{{OP_username}}" }

- name: copy a public key file to remote
  copy: 
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    mode: 0600
  with_items:
    - { "src":"../files/trashMG.pub", "dest":"{{MG_homedir}}/.ssh/authorized_keys", "owner": "{{MG_username}}" }
    - { "src":"../files/tech-user.pub", "dest":"{{tech_homedir}}/.ssh/authorized_keys", "owner": "{{tech_username}}"}
    - { "src":"../files/op-user.pub", "dest":"{{OP_homedir}}/.ssh/authorized_keys", "owner": "{{OP_username}}"}
- name: touch script log file
  file:
    path: "/var/log/script/{{ item }}.log"
    state: touch 
    mode: 0774
    owner: "{{ item }}"
    group: wheel
  with_items:
    - "{{ MG_username }}"
    - "{{ tech_username }}"
    - "{{ OP_username }}"
    - centos


- name: Add SELinux permit rule.
  shell: setenforce 0
